---
fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    translate: 'git://github.com/puppetlabs/puppetlabs-translate.git'
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 5.2.0
